[package]
name = "ant_farm"
version = "0.1.0"
edition = "2018"

[dependencies]
# tui = "*"
legion = "*"
# termion = "*"
rand = "*"
ndarray = "*"
glium = "*"
evo = {path="evo"}
typemap = "*"

[workspace]
members = [
    "evo",
]
